export const SANJI = [
  { value: '煤矿巡检机器人', label: '煤矿巡检机器人' },
  { value: '低压变频调速类', label: '低压变频调速类' },
  { value: '锚固剂类', label: '锚固剂类' },
  { value: '采煤机械化设备及附件', label: '采煤机械化设备及附件' },
  { value: '除（降）尘设备', label: '除（降）尘设备' },
  { value: '架空乘人装置', label: '架空乘人装置' },
  { value: '单绳缠绕提升类', label: '单绳缠绕提升类' },
  { value: '', label: '' },
  { value: '矿车连接件', label: '矿车连接件' },
  { value: '掘进机械化设备', label: '掘进机械化设备' },
  { value: '其它类产品', label: '其它类产品' },
  { value: '通讯系统及装置', label: '通讯系统及装置' },
  { value: '钩头装置', label: '钩头装置' },
  {
    value: '矿用安全、生产监测监控系统',
    label: '矿用安全、生产监测监控系统',
  },
  { value: '电源类', label: '电源类' },
  { value: '电源装置', label: '电源装置' },
  { value: '起动器类', label: '起动器类' },
  { value: '软起动器类', label: '软起动器类' },
  { value: '高压交流变频器类', label: '高压交流变频器类' },
  {
    value: '高压链式静止无功功率发生器类',
    label: '高压链式静止无功功率发生器类',
  },
  { value: '低压无功补偿类', label: '低压无功补偿类' },
  {
    value: '高压变频调速一体式电动机类',
    label: '高压变频调速一体式电动机类',
  },
  { value: '低压变频调速一体式电动机', label: '低压变频调速一体式电动机' },
  { value: '采煤机控制箱类', label: '采煤机控制箱类' },
  { value: '变电类（4000kVA及以下）', label: '变电类（4000kVA及以下）' },
  { value: '特殊变电类', label: '特殊变电类' },
  { value: '防爆配电类', label: '防爆配电类' },
  { value: '一般型配电类', label: '一般型配电类' },
  { value: '保护装置类', label: '保护装置类' },
  { value: '辅助设备类', label: '辅助设备类' },
  { value: '矿灯及其附件类', label: '矿灯及其附件类' },
  { value: '照明设备类', label: '照明设备类' },
  { value: '电机类', label: '电机类' },
  { value: '直流机车设备类', label: '直流机车设备类' },
  { value: '硫化机类', label: '硫化机类' },
  { value: '电动装置类', label: '电动装置类' },
  { value: '锂离子蓄电池类', label: '锂离子蓄电池类' },
  { value: '铅酸蓄电池类', label: '铅酸蓄电池类' },
  { value: '其他电器类', label: '其他电器类' },
  { value: '离心式排水泵类', label: '离心式排水泵类' },
  { value: '潜水泵', label: '潜水泵' },
  { value: '气动泵', label: '气动泵' },
  { value: '往复式泵', label: '往复式泵' },
  { value: '螺杆式泵', label: '螺杆式泵' },
  { value: '柱塞泵', label: '柱塞泵' },
  { value: '柱塞泵站', label: '柱塞泵站' },
  { value: '带式输送机类', label: '带式输送机类' },
  { value: '带式输送机配套件', label: '带式输送机配套件' },
  { value: '刮板输送机（含破碎机）类', label: '刮板输送机（含破碎机）类' },
  { value: '刮板输送机配套件', label: '刮板输送机配套件' },
  { value: '刮板输送机用链，环类产品', label: '刮板输送机用链，环类产品' },
  { value: '矿用离心偶合器摩擦块', label: '矿用离心偶合器摩擦块' },
  { value: '矿用磁力偶合器', label: '矿用磁力偶合器' },
  { value: '矿车类', label: '矿车类' },
  { value: '梭式矿车产品', label: '梭式矿车产品' },
  { value: '人车类', label: '人车类' },
  { value: '电机车类', label: '电机车类' },
  { value: '防爆柴油机', label: '防爆柴油机' },
  { value: '胶轮车类', label: '胶轮车类' },
  { value: '轨道车类', label: '轨道车类' },
  { value: '轮胎式防爆装载机', label: '轮胎式防爆装载机' },
  { value: '铲运机', label: '铲运机' },
  { value: '煤矿用履带式车辆', label: '煤矿用履带式车辆' },
  { value: '无轨车辆', label: '无轨车辆' },
  { value: '多绳摩擦式提升机', label: '多绳摩擦式提升机' },
  {
    value: '矿用提升绞车类（非煤矿山）',
    label: '矿用提升绞车类（非煤矿山）',
  },
  { value: '矿用绞车类', label: '矿用绞车类' },
  { value: '无极绳绞车类', label: '无极绳绞车类' },
  { value: '罐笼类', label: '罐笼类' },
  { value: '箕斗类', label: '箕斗类' },
  { value: '吊桶类', label: '吊桶类' },
  { value: '滚轮罐耳类', label: '滚轮罐耳类' },
  { value: '钢丝绳悬挂装置', label: '钢丝绳悬挂装置' },
  { value: '矿用钢丝绳', label: '矿用钢丝绳' },
  { value: '防坠器', label: '防坠器' },
  { value: '防过卷（过放）装置', label: '防过卷（过放）装置' },
  { value: '跑车防护装置', label: '跑车防护装置' },
  { value: '张力自动平衡悬挂装置', label: '张力自动平衡悬挂装置' },
  { value: '单轨吊', label: '单轨吊' },
  { value: '矿用单轨吊车', label: '矿用单轨吊车' },
  { value: '煤矿井钢丝绳牵引单轨吊车', label: '煤矿井钢丝绳牵引单轨吊车' },
  { value: '给料机', label: '给料机' },
  { value: '无极绳连续牵引车', label: '无极绳连续牵引车' },
  { value: '梭车', label: '梭车' },
  { value: '通风设备', label: '通风设备' },
  { value: '装煤机', label: '装煤机' },
  { value: '装岩设备类', label: '装岩设备类' },
  { value: '巷道修护设备', label: '巷道修护设备' },
  { value: '钻机类产品', label: '钻机类产品' },
  { value: '凿岩具类产品', label: '凿岩具类产品' },
  { value: '钻车类产品', label: '钻车类产品' },
  { value: '液压支架类产品', label: '液压支架类产品' },
  { value: '气垛支架', label: '气垛支架' },
  {
    value: '液压支架立柱、千斤顶类产品',
    label: '液压支架立柱、千斤顶类产品',
  },
  {
    value: '液压支架用阀类、三用阀、注液枪类产品',
    label: '液压支架用阀类、三用阀、注液枪类产品',
  },
  {
    value: '矿用液压支柱、推溜器类产品',
    label: '矿用液压支柱、推溜器类产品',
  },
  { value: '金属顶梁类产品', label: '金属顶梁类产品' },
  { value: '液压支架软管', label: '液压支架软管' },
  { value: '单体支柱柱鞋（帽）', label: '单体支柱柱鞋（帽）' },
  {
    value: '煤矿液压支架用过滤器、煤矿液压支架用过滤站类产品',
    label: '煤矿液压支架用过滤器、煤矿液压支架用过滤站类产品',
  },
  { value: '锚杆类', label: '锚杆类' },
  { value: '锚索、锚具类', label: '锚索、锚具类' },
  {
    value: '张拉机具、测力计、拉力计类',
    label: '张拉机具、测力计、拉力计类',
  },
  { value: '混凝土设备类', label: '混凝土设备类' },
  { value: '工具类', label: '工具类' },
  { value: '井下空气压缩机', label: '井下空气压缩机' },
  { value: '其它类', label: '其它类' },
  { value: '矿用气体测定器类', label: '矿用气体测定器类' },
  { value: '矿用气体检测管', label: '矿用气体检测管' },
  { value: '矿用气体采样器', label: '矿用气体采样器' },
  { value: '气体传感器类', label: '气体传感器类' },
  {
    value: '环境用传感器类（不含气体传感器）',
    label: '环境用传感器类（不含气体传感器）',
  },
  { value: '设备用传感器', label: '设备用传感器' },
  {
    value: '矿用安全、生产监测监控系统配套产品',
    label: '矿用安全、生产监测监控系统配套产品',
  },
  { value: '保护（控制）装置', label: '保护（控制）装置' },
  { value: '保护（控制）装置主机', label: '保护（控制）装置主机' },
  { value: '阻爆、抑爆、泄爆类', label: '阻爆、抑爆、泄爆类' },
  { value: '红外遥控器', label: '红外遥控器' },
  { value: '煤矿用巡检仪', label: '煤矿用巡检仪' },
  { value: '瓦斯抽放设备', label: '瓦斯抽放设备' },
  { value: '水射流增透设备', label: '水射流增透设备' },
  { value: '防灭火装置及设备', label: '防灭火装置及设备' },
  { value: '封孔器', label: '封孔器' },
  { value: '制冷装置类', label: '制冷装置类' },
  { value: '矿用通信分站类', label: '矿用通信分站类' },
  { value: '手持终端类', label: '手持终端类' },
  { value: '矿用信号设备类', label: '矿用信号设备类' },
  { value: '矿用电缆', label: '矿用电缆' },
  { value: '矿用阻燃输送带', label: '矿用阻燃输送带' },
  { value: '矿用导风筒及风筒涂覆布', label: '矿用导风筒及风筒涂覆布' },
  { value: '矿用非金属管材', label: '矿用非金属管材' },
  { value: '其他', label: '其他' },
  { value: '爆炸物品', label: '爆炸物品' },
  { value: '自救器', label: '自救器' },
  { value: '呼吸器', label: '呼吸器' },
  { value: '自动苏生器', label: '自动苏生器' },
  { value: '矿井压风自救装置', label: '矿井压风自救装置' },
  { value: '难燃介质', label: '难燃介质' },
  { value: '起重设备类', label: '起重设备类' },
]
export const ERJI = [
  { value: '煤矿巡检机器人', label: '煤矿巡检机器人' },
  { value: '控制设备', label: '控制设备' },
  { value: '锚喷支护装备', label: '锚喷支护装备' },
  { value: '采煤机械化设备及附件', label: '采煤机械化设备及附件' },
  { value: '除（降）尘设备类', label: '除（降）尘设备类' },
  { value: '架空乘人装置类', label: '架空乘人装置类' },
  { value: '矿用提升机、提升绞车', label: '矿用提升机、提升绞车' },
  { value: '矿车及连接件', label: '矿车及连接件' },
  { value: '掘进机械化设备', label: '掘进机械化设备' },
  { value: '其它类产品', label: '其它类产品' },
  { value: '通讯系统及装置', label: '通讯系统及装置' },
  { value: '提升容器及配套件', label: '提升容器及配套件' },
  {
    value: '矿用安全、生产监测监控系统',
    label: '矿用安全、生产监测监控系统',
  },
  { value: '电源', label: '电源' },
  { value: '变电设备', label: '变电设备' },
  { value: '配电设备', label: '配电设备' },
  { value: '保护装置类', label: '保护装置类' },
  { value: '辅助设备', label: '辅助设备' },
  { value: '矿灯及其附件', label: '矿灯及其附件' },
  { value: '照明设备', label: '照明设备' },
  { value: '电机', label: '电机' },
  { value: '直流机车设备类', label: '直流机车设备类' },
  { value: '其他', label: '其他' },
  { value: '矿用电池', label: '矿用电池' },
  { value: '其他电器类', label: '其他电器类' },
  { value: '离心式排水泵', label: '离心式排水泵' },
  { value: '潜水泵类', label: '潜水泵类' },
  { value: '气动泵类', label: '气动泵类' },
  { value: '其他泵类', label: '其他泵类' },
  { value: '带式输送机类及配套件', label: '带式输送机类及配套件' },
  {
    value: '刮板输送机（含破碎机）类及配套件',
    label: '刮板输送机（含破碎机）类及配套件',
  },
  { value: '人车', label: '人车' },
  { value: '电机车', label: '电机车' },
  { value: '防爆柴油机（车）', label: '防爆柴油机（车）' },
  { value: '矿用钢丝绳', label: '矿用钢丝绳' },
  { value: '提升安全保护装置类', label: '提升安全保护装置类' },
  { value: '单轨吊类', label: '单轨吊类' },
  { value: '给料机', label: '给料机' },
  { value: '牵引车类', label: '牵引车类' },
  { value: '梭车', label: '梭车' },
  { value: '通风设备类', label: '通风设备类' },
  { value: '装煤设备类', label: '装煤设备类' },
  { value: '钻孔机械、机具及附件', label: '钻孔机械、机具及附件' },
  { value: '液压支护设备及附件', label: '液压支护设备及附件' },
  { value: '工具类', label: '工具类' },
  { value: '井下空气压缩机', label: '井下空气压缩机' },
  { value: '其它', label: '其它' },
  {
    value: '矿用安全检测、监测仪器仪表',
    label: '矿用安全检测、监测仪器仪表',
  },
  { value: '传感器类', label: '传感器类' },
  {
    value: '矿用安全、生产监测监控系统配套产品',
    label: '矿用安全、生产监测监控系统配套产品',
  },
  { value: '保护（控制）装置', label: '保护（控制）装置' },
  { value: '阻爆、抑爆、泄爆类', label: '阻爆、抑爆、泄爆类' },
  { value: '其他类', label: '其他类' },
  { value: '煤矿用巡检仪', label: '煤矿用巡检仪' },
  { value: '瓦斯抽放设备类', label: '瓦斯抽放设备类' },
  { value: '防灭火装置及设备类', label: '防灭火装置及设备类' },
  { value: '封孔器类', label: '封孔器类' },
  { value: '制冷、冷却装置', label: '制冷、冷却装置' },
  { value: '矿用通信分站类', label: '矿用通信分站类' },
  { value: '手持终端类', label: '手持终端类' },
  { value: '矿用信号设备类', label: '矿用信号设备类' },
  { value: '矿用电缆类', label: '矿用电缆类' },
  { value: '矿用阻燃输送带类', label: '矿用阻燃输送带类' },
  {
    value: '矿用导风筒及风筒涂覆布类',
    label: '矿用导风筒及风筒涂覆布类',
  },
  { value: '矿用非金属管材类', label: '矿用非金属管材类' },
  { value: '爆炸物品类', label: '爆炸物品类' },
  { value: '自救器', label: '自救器' },
  { value: '呼吸器', label: '呼吸器' },
  { value: '自动苏生器', label: '自动苏生器' },
  { value: '其他应急救援设备', label: '其他应急救援设备' },
  { value: '难燃介质', label: '难燃介质' },
  { value: '起重设备', label: '起重设备' },
]
export const YIJI = [
  {
    value: '矿用安全检测、监测仪器仪表及监控系统',
    label: '矿用安全检测、监测仪器仪表及监控系统',
  },
  { value: '矿用电气设备', label: '矿用电气设备' },
  { value: '矿用采掘与支护设备', label: '矿用采掘与支护设备' },
  { value: '矿用通风防尘设备', label: '矿用通风防尘设备' },
  { value: '矿用提升运输设备', label: '矿用提升运输设备' },
  { value: '其它类产品', label: '其它类产品' },
  { value: '矿用通信、信号设备', label: '矿用通信、信号设备' },
  { value: '矿用排水设备', label: '矿用排水设备' },
  { value: '煤矿安全设施及装置', label: '煤矿安全设施及装置' },
  { value: '矿用非金属制品', label: '矿用非金属制品' },
  { value: '矿用爆破器材', label: '矿用爆破器材' },
  { value: '矿用应急救援设备', label: '矿用应急救援设备' },
  { value: '其它', label: '其它' },
]
